name: Deploy to Heroku

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: Heroku # Github secret environment name
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # Github action from the marketplace
        with:
          heroku_api_key: ${{secrets.API_KEY}}
          heroku_app_name: "shareameal-tg" 
          heroku_email: ${{secrets.EMAIL}}